server:
  port: 8082

#eureca name of instance
spring:
  application:
    name: Flights-Service
 
  
#Spring data mongodb
  data:
    mongodb:
      uri: mongodb+srv://Test_Admin:Test_pass@first-cluster.phl9p.mongodb.net/test
      database: FlightBookingSystem